# Generated by Django 3.0 on 2020-02-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='creation_dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
